<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Root_Dispatcher'     => __DIR__ . '/root_Dispatcher.php',
    'Root_Controller'     => __DIR__ . '/root_Controller.php',
    'Users'               => __DIR__ . '/admin/users/users_Model.php',
    'Users_Dispatcher'    => __DIR__ . '/admin/users/users_Dispatcher.php',
    'Users_Controller'    => __DIR__ . '/admin/users/users_Controller.php',
    'Admin_Controller'    => __DIR__ . '/admin/admin_Controller.php',
    'Htpasswd_Dispatcher' => __DIR__ . '/admin/htpasswd/htpasswd_Dispatcher.php',
    'Htpasswd_Controller' => __DIR__ . '/admin/htpasswd/htpasswd_Controller.php',
    'Htpasswd'            => __DIR__ . '/admin/htpasswd/htpasswd_Model.php',
    'Groups_Dispatcher'   => __DIR__ . '/admin/groups/groups_Dispatcher.php',
    'Groups'              => __DIR__ . '/admin/groups/groups_Model.php',
    'Groups_Controller'   => __DIR__ . '/admin/groups/groups_Controller.php',
    'Admin'               => __DIR__ . '/admin/admin_Model.php',
    'Rights_Controller'   => __DIR__ . '/admin/rights/rights_Controller.php',
    'Rights_Dispatcher'   => __DIR__ . '/admin/rights/rights_Dispatcher.php',
    'Rights'              => __DIR__ . '/admin/rights/rights_Model.php',
    'Admin_Dispatcher'    => __DIR__ . '/admin/admin_Dispatcher.php',
);