<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Knb_Controller'      => __DIR__ . '/Controller.php',
    'Knb_Right'           => __DIR__ . '/Models/Right.php',
    'Knb_RightTable'      => __DIR__ . '/Models/RightTable.php',
    'Knb_UserTable'       => __DIR__ . '/Models/UserTable.php',
    'Knb_Group'           => __DIR__ . '/Models/Group.php',
    'Knb_Session'         => __DIR__ . '/Models/Session.php',
    'Knb_SessionTable'    => __DIR__ . '/Models/SessionTable.php',
    'Knb_User'            => __DIR__ . '/Models/User.php',
    'Knb_GroupTable'      => __DIR__ . '/Models/GroupTable.php',
    'Knb_Error'           => __DIR__ . '/Error.php',
    'Knb_FrontController' => __DIR__ . '/FrontController.php',
    'Knb_Cookie'          => __DIR__ . '/Cookie.php',
    'Knb_AbstractTable'   => __DIR__ . '/AbstractTable.php',
    'Knb_ConnectedUser'   => __DIR__ . '/ConnectedUser.php',
);