<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vbf_MySQL'               => __DIR__ . '/MySQL.php',
    'Path'                    => __DIR__ . '/Path.php',
    'Vbf_Guard'               => __DIR__ . '/Guard.php',
    'Vbf_Skins'               => __DIR__ . '/Skins.php',
    'Vbf_Image'               => __DIR__ . '/Image.php',
    'Vbf_Mvc_Controller'      => __DIR__ . '/Mvc/Controller.php',
    'Vbf_Mvc_View'            => __DIR__ . '/Mvc/View.php',
    'Vbf_Mvc_FrontController' => __DIR__ . '/Mvc/FrontController.php',
    'Vbf_Mvc_Exception404'    => __DIR__ . '/Mvc/Exception404.php',
    'Vbf_Mvc_Dispatcher'      => __DIR__ . '/Mvc/Dispatcher.php',
    'Vbf_GuardProxy'          => __DIR__ . '/GuardProxy.php',
);